language: java
jdk:
- oraclejdk8
script: mvn clean verify
branches:
  only:
  - master
notifications:
  email: false
env:
  global:
  - secure: WfyDydbmUIuauwdXKbg2w41DL+9mHi3/A4Sf25kpC8L9kgiR/hmVK1q8lR9Wk2qfcm4s9ERDWS+SoqrOlXzkptBnIJTp6+chC7BPUms1EnQqUWWz+1kygamPua5u+JsX7KPUnHuqBKxsGSX1JiIErH9Dx0t3rXWfOxrEgg4GWDltEA/Z0YORNv3STWqDWD2WIllHnM9uql4dj+cg6kPdol0i2bmQNZ5rZsG5L9JRT8ji5vsuQhNh1Ne5rs05MC2agUc5a1WYBdt9orSTl4o519zR7rzrqCdehHYgAZR4OQfiuio78TDKuF/0YdyC0v1yXiJcZ1PkqgGrMWEHh/Xj7CqZRdpxaBKEgDs20pLz6qsqe2GqLQZpzuP3GNqd3Vn7V3RSNCzQoQZJqZ5o3FmkMtGl1K7VXOYCa+nP1x2cJOLDCXPI9zQgbg2aPFjEXv/W56KghMQRnBndylQdhoDfHZH/GT65hB9P6nQnTRNC4cycWsN2zBA4/TVLS7MLdZlcy4xV0RieTqOAzprdeaPTjiOvegZbh3+LsKmgFWB8IDAQ3OmieDoLccxDd6pU+XugZuOJMESCPrLEhObdaFZVlSL68UgNjY9jw63yrDzWvrek1VKgzKK03aliqY8J8TMenEakgevXZWsPhd4WewiGGk6+ojrokPbU9spqUL0aRgE=
  - secure: HPXO/e3/s1QsZECSOlZ6bNYZ+YoTKNAvZ76rOrPw/8IPlRiH5maFLrrsGIzj/d9auOfdg+264YxVvBP9BhNUN2iEoiBh9J0iYvKJdJYRy8aKlhcYq6OK7FTKe1dECHYAboJBCFHsRl9w93FlJred9fXO1nMon6L0MnmxSMjM+AENdxQ02Wq37g3Dvecsii4cw19NjUPbv8ABI2LqWQmC7WTFzalDDj0gJBE4XiHzwPORe+FboQFlfCiGgDb+BQ+uWp0QjHpYqVe0q1MXP7qknxbWUQUimmxPqbZDTcCN1s1YruMTLELxvihFajGxK5py/5+W5DPzA+m9u0c16FezuBP2HYrzvcZYQTo8O35B7Duv3bd1bwmwIoFUy2tfNRGSJ7yEK/wyUJkp5n81IlP4jE9N8cy4g/dEJQ1EbbaA+uP5eQsB7ggrSP8ajlUanF/o3ayhuG44/NO2nCX1zTQo0toaUOIC9TZ5p6hN/UjHii0bBU1SvZ6QPoYk2ELx57fYyFtGr/ffNrBHraVAisVkw//PwcMFn5zlhnaSiRjoTM8IV3HCS4lZTC/pA4L3WkqHLdaajmxIljVCqKOvGxkc33XwM/8yikmOgSY0lqwBGB7sLF86D1QVPy8GxgVmCKyHIyaWATuufbAhgTndNXFp+qPAWmdXd5zN7Elo9aBHvJU=
after_success:
    "curl -T CinemApp-ear/target/CinemApp.ear -u $FTP_USER:$FTP_PASSWORD ftp://5.249.154.6/deployments/"